name: Deploy
on: [push]

env:
  AWS_REGION: ap-south-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Node.js 14.15
      uses: actions/setup-node@v2
      with:
        node-version: 14.15

    - name: Install Serverless
      run: |
        sudo npm config set prefix /usr/bin
        sudo npm install -g serverless

    - name: setup-docker
      uses: docker-practice/actions-setup-docker@v1

    - name: Install Serverless plugins
      run: |
        sudo npm install serverless-iam-roles-per-function --save-dev
        sudo npm install serverless-offline --save-dev
        sudo npm install --save serverless-python-requirements

    - name: Serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
